
## makeCacheMatrix returns a list of the functions set, get, setInverse and getInverse

makeCacheMatrix <- function(x = matrix()) {
	 i <- NULL
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
    get <- function() x 
	setInverse <- function(solve) {i <<- solve}
	getInverse <- function() i 
	list(set = set, get = get,
             setInverse = setInverse,
             getInverse = getInverse)


}


## cacheSolve takes the list of functions generated by makeCacheMatrix, for each input determines if it has already calculated the matrix and if not calculates the inverse using the function solve(x)

cacheSolve <- function(x, ...) {
	i <- x$getInverse()

	if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
	data <- x$get()

	
        i <- solve(data)
        x$setInverse(i)
        i

}
